export const animationTexts = [
  'Welcome To Supra LLM!',
  1000,
  'Welcome To Finland!',
  1000,
  'Help me find the best Chinese restaurant in Helsinki',
  1000,
  'Help me find the best Vietnamese restaurant in Helsinki',
  1000,
  'Help me find the best Finnish restaurant in Helsinki',
  1000,
  'Help me find the best café in Helsinki',
  1000,
  'What is the most common sport in Finland',
  1000,
  'What is the most famous cuisine in Finland',
  1000,
  'Show me historic sites in Finland',
  1000,
  'Show me beautiful attractions in Helsinki',
  1000,
  'I like to hear more about Finland',
  1000,
];
